# Generated by Django 3.1.7 on 2021-04-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockscraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Blog',
        ),
    ]
